services:
  - type: web
    name: ikraland
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8000
      - key: APP_KEY
        value: base64:y522XldlAKup6IxEKYBj6PKUfYtC/NOCDstQNSfOfvY=
