# Gunakan PHP image dengan Composer & Extensions Laravel
FROM php:8.2-fpm

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    zip \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    libzip-dev \
    && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd zip

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Set working directory
WORKDIR /var/www

# Copy project
COPY . .

# Install dependencies
RUN composer install

# Generate Laravel key
RUN php artisan key:generate

# Set permissions
RUN chmod -R 755 /var/www/storage

# Expose port (Railway butuh ini)
EXPOSE 8000

# Start server
CMD php artisan serve --host=0.0.0.0 --port=8000
