FROM php:8.2-cli

# Install dependencies
RUN apt-get update && apt-get install -y unzip git curl libzip-dev zip && docker-php-ext-install zip

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Copy project
WORKDIR /app
COPY . .

# Install dependencies
RUN composer install

# Expose port
EXPOSE 8000

# Start Laravel
CMD php artisan serve --host=0.0.0.0 --port=8000
